import {all} from 'redux-saga/effects';

import {
    watchAuthSaga,
    watchUserInfoSaga,
    watchUserInfoFullSaga,
    watchUserInfoFullUpdateSaga,
    watchSendEmailSaga,
    watchUploadPhotoSaga,
    watchDialogsSaga,
    watchDialogSaga,
    watchMessageSendSaga,
    watchSaveTokenSaga,
    watchRegisterInfoSaga,
    watchRegisterSaga,
    watchCheckCodeSaga,
    watchGetCodeSaga,
    watchPasswordResetSaga,
    watchDialogDeleteSaga,
    watchSpecsSaga,
    watchSpecsSetSaga,
    watchProfileDescriptionsSaga,
    watchProfileDescriptionUpdateSaga,
    watchGetWorkspacesSaga,
    watchBeautyRoomsSaga,
    watchCityInfoSaga,
    watchWorkspaceAddSaga,
    watchWorkspaceDeleteSaga,
    watchBeautyRoomSendSaga,
    watchWorkplaceUpdateSaga,
    watchPriceSaga,
} from './user';

export default function* rootSaga() {
    yield all([
        // user
        watchAuthSaga(),
        watchUserInfoSaga(),
        watchUserInfoFullSaga(),
        watchUserInfoFullUpdateSaga(),
        watchSendEmailSaga(),
        watchUploadPhotoSaga(),
        watchDialogsSaga(),
        watchDialogSaga(),
        watchMessageSendSaga(),
        watchSaveTokenSaga(),
        watchRegisterInfoSaga(),
        watchRegisterSaga(),
        watchCheckCodeSaga(),
        watchGetCodeSaga(),
        watchPasswordResetSaga(),
        watchDialogDeleteSaga(),
        watchSpecsSaga(),
        watchSpecsSetSaga(),
        watchProfileDescriptionsSaga(),
        watchProfileDescriptionUpdateSaga(),
        watchGetWorkspacesSaga(),
        watchBeautyRoomsSaga(),
        watchCityInfoSaga(),
        watchWorkspaceAddSaga(),
        watchWorkspaceDeleteSaga(),
        watchBeautyRoomSendSaga(),
        watchWorkplaceUpdateSaga(),
        watchPriceSaga(),
    ]);
}
